version: '3'
services:

  webapp:
    build: .
    tty: true
    env_file:
      - .env
    command: 
      python src/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    working_dir: /webapp
    networks:
      - backend

  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - backend

networks:
  backend:
