not_valid_username_or_password = "Неверное имя пользователя или пароль"
not_valid_data = "Введены некорректные данные"
username_is_used = "Пользователь с таким именем уже существует"
email_is_used = "Пользователь с таким email уже существует"
not_valid_verification_code = "Введен неверный проверочный код"
email_is_not_used = "Пользователь с таким email не существует"
not_equals_password_confirm_password = "Пароли не совпадают"
