# Generated by Django 4.0.1 on 2022-01-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
