# Generated by Django 4.0.1 on 2022-01-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_wish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='img/'),
        ),
    ]
