# Generated by Django 4.0.1 on 2022-01-30 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_wish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wish',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wish',
            name='link',
            field=models.CharField(default='', max_length=50),
        ),
    ]
