# Generated by Django 4.0.1 on 2022-01-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_wish_data_wish_username_alter_wish_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='type',
            field=models.CharField(default='Разное', max_length=50),
        ),
    ]
