# Generated by Django 4.0.1 on 2022-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_wish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='img/'),
        ),
    ]
