# Generated by Django 4.0.1 on 2022-01-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_wish_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='image',
            field=models.ImageField(default='static/default.jpg', upload_to='img/'),
        ),
    ]
